// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Zoka_GUI

#include "../ui.h"

void ui_BootScreen_screen_init(void)
{
ui_BootScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_BootScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BootScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BootScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BootImage = lv_img_create(ui_BootScreen);
lv_img_set_src(ui_BootImage, &ui_img_m_png);
lv_obj_set_width( ui_BootImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BootImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BootImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BootImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BootImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_BootImage,200);

ui_BootBar = lv_bar_create(ui_BootScreen);
lv_bar_set_value(ui_BootBar,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BootBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BootBar, 250);
lv_obj_set_height( ui_BootBar, 20);
lv_obj_set_x( ui_BootBar, 0 );
lv_obj_set_y( ui_BootBar, 300 );
lv_obj_set_align( ui_BootBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_BootBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_BootBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_BootBar, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_BootBar, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_PRIMARY);

}
