// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Zoka_GUI

#include "../ui.h"

void ui_MainScreen1_screen_init(void)
{
ui_MainScreen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainScreen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusBar = ui_StatusBar_create(ui_MainScreen1);
lv_obj_set_x( ui_StatusBar, 0 );
lv_obj_set_y( ui_StatusBar, 0 );
lv_obj_set_align( ui_StatusBar, LV_ALIGN_TOP_MID );






ui_AltitudeRoller1 = lv_roller_create(ui_MainScreen1);
lv_roller_set_options( ui_AltitudeRoller1, "15\n10\n5\n0\n-5\n-10\n-15\n-20\n-25\n-30\n-35\n-40\n-45\n-50\n-55\n-60\n-65\n-70\n-75\n-80\n-85\n-90\n-100\n-105\n-100\n", LV_ROLLER_MODE_NORMAL );
lv_roller_set_selected( ui_AltitudeRoller1, 3, LV_ANIM_OFF);
lv_obj_set_height( ui_AltitudeRoller1, 100);
lv_obj_set_width( ui_AltitudeRoller1, lv_pct(14));
lv_obj_set_x( ui_AltitudeRoller1, 319 );
lv_obj_set_y( ui_AltitudeRoller1, -391 );
lv_obj_set_align( ui_AltitudeRoller1, LV_ALIGN_CENTER );

ui_FOV_Navigation = lv_obj_create(ui_MainScreen1);
lv_obj_remove_style_all(ui_FOV_Navigation);
lv_obj_set_width( ui_FOV_Navigation, 750);
lv_obj_set_height( ui_FOV_Navigation, 960);
lv_obj_set_x( ui_FOV_Navigation, 0 );
lv_obj_set_y( ui_FOV_Navigation, -3 );
lv_obj_set_align( ui_FOV_Navigation, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_FOV_Navigation, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOV_Navigation, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOV_Navigation, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOV_Navigation, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVNAV_TOP_LEFT = lv_obj_create(ui_FOV_Navigation);
lv_obj_remove_style_all(ui_FOVNAV_TOP_LEFT);
lv_obj_set_width( ui_FOVNAV_TOP_LEFT, lv_pct(25));
lv_obj_set_height( ui_FOVNAV_TOP_LEFT, lv_pct(25));
lv_obj_set_x( ui_FOVNAV_TOP_LEFT, lv_pct(-30) );
lv_obj_set_y( ui_FOVNAV_TOP_LEFT, lv_pct(-35) );
lv_obj_set_align( ui_FOVNAV_TOP_LEFT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVNAV_TOP_LEFT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVNAV_TOP_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVNAV_TOP_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVNAV_TOP_LEFT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeOfArival = lv_label_create(ui_FOVNAV_TOP_LEFT);
lv_obj_set_width( ui_TimeOfArival, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeOfArival, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimeOfArival, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeOfArival,"10:20");
ui_object_set_themeable_style_property(ui_TimeOfArival, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_TimeOfArival, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_PRIMARY);
lv_obj_set_style_text_font(ui_TimeOfArival, &ui_font_Lexend50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVNAV_TOP_MIDDLE = lv_obj_create(ui_FOV_Navigation);
lv_obj_remove_style_all(ui_FOVNAV_TOP_MIDDLE);
lv_obj_set_width( ui_FOVNAV_TOP_MIDDLE, lv_pct(22));
lv_obj_set_height( ui_FOVNAV_TOP_MIDDLE, lv_pct(25));
lv_obj_set_x( ui_FOVNAV_TOP_MIDDLE, lv_pct(0) );
lv_obj_set_y( ui_FOVNAV_TOP_MIDDLE, lv_pct(-35) );
lv_obj_set_align( ui_FOVNAV_TOP_MIDDLE, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVNAV_TOP_MIDDLE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVNAV_TOP_MIDDLE, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVNAV_TOP_MIDDLE, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVNAV_TOP_MIDDLE, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TImeRemaining = lv_label_create(ui_FOVNAV_TOP_MIDDLE);
lv_obj_set_width( ui_TImeRemaining, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TImeRemaining, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TImeRemaining, LV_ALIGN_CENTER );
lv_label_set_text(ui_TImeRemaining,"0:05");
ui_object_set_themeable_style_property(ui_TImeRemaining, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_TImeRemaining, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_PRIMARY);
lv_obj_set_style_text_font(ui_TImeRemaining, &ui_font_Lexend50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVNAV_TOP_RIGHT = lv_obj_create(ui_FOV_Navigation);
lv_obj_remove_style_all(ui_FOVNAV_TOP_RIGHT);
lv_obj_set_width( ui_FOVNAV_TOP_RIGHT, lv_pct(29));
lv_obj_set_height( ui_FOVNAV_TOP_RIGHT, lv_pct(25));
lv_obj_set_x( ui_FOVNAV_TOP_RIGHT, lv_pct(30) );
lv_obj_set_y( ui_FOVNAV_TOP_RIGHT, lv_pct(-35) );
lv_obj_set_align( ui_FOVNAV_TOP_RIGHT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVNAV_TOP_RIGHT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVNAV_TOP_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVNAV_TOP_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVNAV_TOP_RIGHT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RemainingDistance = lv_label_create(ui_FOVNAV_TOP_RIGHT);
lv_obj_set_width( ui_RemainingDistance, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RemainingDistance, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RemainingDistance, LV_ALIGN_CENTER );
lv_label_set_text(ui_RemainingDistance,"1000 km");
ui_object_set_themeable_style_property(ui_RemainingDistance, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_RemainingDistance, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_PRIMARY);
lv_obj_set_style_text_font(ui_RemainingDistance, &ui_font_Lexend50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVNAV_CENTER = lv_obj_create(ui_FOV_Navigation);
lv_obj_remove_style_all(ui_FOVNAV_CENTER);
lv_obj_set_width( ui_FOVNAV_CENTER, lv_pct(80));
lv_obj_set_height( ui_FOVNAV_CENTER, lv_pct(30));
lv_obj_set_align( ui_FOVNAV_CENTER, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVNAV_CENTER, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVNAV_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVNAV_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVNAV_CENTER, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVNAV_BOTTOM_LEFT = lv_obj_create(ui_FOV_Navigation);
lv_obj_remove_style_all(ui_FOVNAV_BOTTOM_LEFT);
lv_obj_set_width( ui_FOVNAV_BOTTOM_LEFT, lv_pct(25));
lv_obj_set_height( ui_FOVNAV_BOTTOM_LEFT, lv_pct(20));
lv_obj_set_x( ui_FOVNAV_BOTTOM_LEFT, lv_pct(-25) );
lv_obj_set_y( ui_FOVNAV_BOTTOM_LEFT, lv_pct(35) );
lv_obj_set_align( ui_FOVNAV_BOTTOM_LEFT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVNAV_BOTTOM_LEFT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVNAV_BOTTOM_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVNAV_BOTTOM_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVNAV_BOTTOM_LEFT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArcSpeed = lv_arc_create(ui_FOVNAV_BOTTOM_LEFT);
lv_obj_set_width( ui_ArcSpeed, lv_pct(100));
lv_obj_set_height( ui_ArcSpeed, lv_pct(100));
lv_obj_set_align( ui_ArcSpeed, LV_ALIGN_CENTER );
lv_arc_set_value(ui_ArcSpeed, 50);
ui_object_set_themeable_style_property(ui_ArcSpeed, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_SECONDARY);
ui_object_set_themeable_style_property(ui_ArcSpeed, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_SECONDARY);

ui_object_set_themeable_style_property(ui_ArcSpeed, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_ArcSpeed, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_PRIMARY);

lv_obj_set_style_bg_color(ui_ArcSpeed, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcSpeed, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SpeedLabel = lv_label_create(ui_ArcSpeed);
lv_obj_set_width( ui_SpeedLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedLabel, 0 );
lv_obj_set_y( ui_SpeedLabel, -5 );
lv_obj_set_align( ui_SpeedLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedLabel,"135");
ui_object_set_themeable_style_property(ui_SpeedLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_SpeedLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_PRIMARY);
lv_obj_set_style_text_font(ui_SpeedLabel, &ui_font_Lexend50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UnitLabel = lv_label_create(ui_ArcSpeed);
lv_obj_set_width( ui_UnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_UnitLabel, 1 );
lv_obj_set_y( ui_UnitLabel, 55 );
lv_obj_set_align( ui_UnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_UnitLabel,"Km/h");
ui_object_set_themeable_style_property(ui_UnitLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_UnitLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_PRIMARY);
lv_obj_set_style_text_font(ui_UnitLabel, &ui_font_Lexend32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FONAV_BOTTOM_RIGHT = lv_obj_create(ui_FOV_Navigation);
lv_obj_remove_style_all(ui_FONAV_BOTTOM_RIGHT);
lv_obj_set_width( ui_FONAV_BOTTOM_RIGHT, lv_pct(35));
lv_obj_set_height( ui_FONAV_BOTTOM_RIGHT, lv_pct(25));
lv_obj_set_x( ui_FONAV_BOTTOM_RIGHT, lv_pct(25) );
lv_obj_set_y( ui_FONAV_BOTTOM_RIGHT, lv_pct(35) );
lv_obj_set_align( ui_FONAV_BOTTOM_RIGHT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FONAV_BOTTOM_RIGHT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FONAV_BOTTOM_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FONAV_BOTTOM_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FONAV_BOTTOM_RIGHT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_img_create(ui_FONAV_BOTTOM_RIGHT);
lv_img_set_src(ui_Image5, &ui_img_speed_limit_png);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 576
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 576
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image5,70);
ui_object_set_themeable_style_property(ui_Image5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_Image5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_PRIMARY);

ui_SpeedLimitLabel = lv_label_create(ui_Image5);
lv_obj_set_width( ui_SpeedLimitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedLimitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedLimitLabel, 0 );
lv_obj_set_y( ui_SpeedLimitLabel, 4 );
lv_obj_set_align( ui_SpeedLimitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedLimitLabel,"135");
ui_object_set_themeable_style_property(ui_SpeedLimitLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_SpeedLimitLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_PRIMARY);
lv_obj_set_style_text_font(ui_SpeedLimitLabel, &ui_font_Lexend50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCYCLING_Space = lv_obj_create(ui_MainScreen1);
lv_obj_remove_style_all(ui_FOVCYCLING_Space);
lv_obj_set_width( ui_FOVCYCLING_Space, 753);
lv_obj_set_height( ui_FOVCYCLING_Space, 968);
lv_obj_set_x( ui_FOVCYCLING_Space, -2 );
lv_obj_set_y( ui_FOVCYCLING_Space, 1 );
lv_obj_set_align( ui_FOVCYCLING_Space, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_FOVCYCLING_Space, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_FOVCYCLING_Space, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCYCLING_Space, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCYCLING_Space, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCYCLING_Space, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCYCLING_TOP_LEFT = lv_obj_create(ui_FOVCYCLING_Space);
lv_obj_remove_style_all(ui_FOVCYCLING_TOP_LEFT);
lv_obj_set_width( ui_FOVCYCLING_TOP_LEFT, lv_pct(35));
lv_obj_set_height( ui_FOVCYCLING_TOP_LEFT, lv_pct(25));
lv_obj_set_x( ui_FOVCYCLING_TOP_LEFT, lv_pct(-25) );
lv_obj_set_y( ui_FOVCYCLING_TOP_LEFT, lv_pct(-35) );
lv_obj_set_align( ui_FOVCYCLING_TOP_LEFT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCYCLING_TOP_LEFT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCYCLING_TOP_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCYCLING_TOP_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCYCLING_TOP_LEFT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCYCLING_TOP_RIGHT = lv_obj_create(ui_FOVCYCLING_Space);
lv_obj_remove_style_all(ui_FOVCYCLING_TOP_RIGHT);
lv_obj_set_width( ui_FOVCYCLING_TOP_RIGHT, lv_pct(35));
lv_obj_set_height( ui_FOVCYCLING_TOP_RIGHT, lv_pct(25));
lv_obj_set_x( ui_FOVCYCLING_TOP_RIGHT, lv_pct(25) );
lv_obj_set_y( ui_FOVCYCLING_TOP_RIGHT, lv_pct(-35) );
lv_obj_set_align( ui_FOVCYCLING_TOP_RIGHT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCYCLING_TOP_RIGHT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCYCLING_TOP_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCYCLING_TOP_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCYCLING_TOP_RIGHT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCYCLING_CENTER = lv_obj_create(ui_FOVCYCLING_Space);
lv_obj_remove_style_all(ui_FOVCYCLING_CENTER);
lv_obj_set_width( ui_FOVCYCLING_CENTER, lv_pct(80));
lv_obj_set_height( ui_FOVCYCLING_CENTER, lv_pct(30));
lv_obj_set_align( ui_FOVCYCLING_CENTER, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCYCLING_CENTER, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCYCLING_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCYCLING_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCYCLING_CENTER, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCYCLING_BOTTOM_LEFT = lv_obj_create(ui_FOVCYCLING_Space);
lv_obj_remove_style_all(ui_FOVCYCLING_BOTTOM_LEFT);
lv_obj_set_width( ui_FOVCYCLING_BOTTOM_LEFT, lv_pct(25));
lv_obj_set_height( ui_FOVCYCLING_BOTTOM_LEFT, lv_pct(25));
lv_obj_set_x( ui_FOVCYCLING_BOTTOM_LEFT, lv_pct(-30) );
lv_obj_set_y( ui_FOVCYCLING_BOTTOM_LEFT, lv_pct(35) );
lv_obj_set_align( ui_FOVCYCLING_BOTTOM_LEFT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCYCLING_BOTTOM_LEFT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCYCLING_BOTTOM_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCYCLING_BOTTOM_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCYCLING_BOTTOM_LEFT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCYCLING_BOTTOM_MIDDLE = lv_obj_create(ui_FOVCYCLING_Space);
lv_obj_remove_style_all(ui_FOVCYCLING_BOTTOM_MIDDLE);
lv_obj_set_width( ui_FOVCYCLING_BOTTOM_MIDDLE, lv_pct(25));
lv_obj_set_height( ui_FOVCYCLING_BOTTOM_MIDDLE, lv_pct(25));
lv_obj_set_x( ui_FOVCYCLING_BOTTOM_MIDDLE, lv_pct(0) );
lv_obj_set_y( ui_FOVCYCLING_BOTTOM_MIDDLE, lv_pct(35) );
lv_obj_set_align( ui_FOVCYCLING_BOTTOM_MIDDLE, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCYCLING_BOTTOM_MIDDLE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCYCLING_BOTTOM_MIDDLE, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCYCLING_BOTTOM_MIDDLE, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCYCLING_BOTTOM_MIDDLE, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCYCLING_BOTTOM_RIGHT = lv_obj_create(ui_FOVCYCLING_Space);
lv_obj_remove_style_all(ui_FOVCYCLING_BOTTOM_RIGHT);
lv_obj_set_width( ui_FOVCYCLING_BOTTOM_RIGHT, lv_pct(25));
lv_obj_set_height( ui_FOVCYCLING_BOTTOM_RIGHT, lv_pct(25));
lv_obj_set_x( ui_FOVCYCLING_BOTTOM_RIGHT, lv_pct(30) );
lv_obj_set_y( ui_FOVCYCLING_BOTTOM_RIGHT, lv_pct(35) );
lv_obj_set_align( ui_FOVCYCLING_BOTTOM_RIGHT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCYCLING_BOTTOM_RIGHT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCYCLING_BOTTOM_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCYCLING_BOTTOM_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCYCLING_BOTTOM_RIGHT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCUSTOM_Space = lv_obj_create(ui_MainScreen1);
lv_obj_remove_style_all(ui_FOVCUSTOM_Space);
lv_obj_set_width( ui_FOVCUSTOM_Space, 753);
lv_obj_set_height( ui_FOVCUSTOM_Space, 968);
lv_obj_set_x( ui_FOVCUSTOM_Space, -2 );
lv_obj_set_y( ui_FOVCUSTOM_Space, 1 );
lv_obj_set_align( ui_FOVCUSTOM_Space, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_FOVCUSTOM_Space, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_FOVCUSTOM_Space, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCUSTOM_Space, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCUSTOM_Space, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCUSTOM_Space, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCUSTOM_TOP_LEFT = lv_obj_create(ui_FOVCUSTOM_Space);
lv_obj_remove_style_all(ui_FOVCUSTOM_TOP_LEFT);
lv_obj_set_width( ui_FOVCUSTOM_TOP_LEFT, lv_pct(25));
lv_obj_set_height( ui_FOVCUSTOM_TOP_LEFT, lv_pct(25));
lv_obj_set_x( ui_FOVCUSTOM_TOP_LEFT, lv_pct(-30) );
lv_obj_set_y( ui_FOVCUSTOM_TOP_LEFT, lv_pct(-35) );
lv_obj_set_align( ui_FOVCUSTOM_TOP_LEFT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCUSTOM_TOP_LEFT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCUSTOM_TOP_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCUSTOM_TOP_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCUSTOM_TOP_LEFT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCUSTOM_TOP_MIDDLE = lv_obj_create(ui_FOVCUSTOM_Space);
lv_obj_remove_style_all(ui_FOVCUSTOM_TOP_MIDDLE);
lv_obj_set_width( ui_FOVCUSTOM_TOP_MIDDLE, lv_pct(25));
lv_obj_set_height( ui_FOVCUSTOM_TOP_MIDDLE, lv_pct(25));
lv_obj_set_x( ui_FOVCUSTOM_TOP_MIDDLE, lv_pct(0) );
lv_obj_set_y( ui_FOVCUSTOM_TOP_MIDDLE, lv_pct(-35) );
lv_obj_set_align( ui_FOVCUSTOM_TOP_MIDDLE, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCUSTOM_TOP_MIDDLE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCUSTOM_TOP_MIDDLE, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCUSTOM_TOP_MIDDLE, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCUSTOM_TOP_MIDDLE, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCUSTOM_TOP_RIGHT = lv_obj_create(ui_FOVCUSTOM_Space);
lv_obj_remove_style_all(ui_FOVCUSTOM_TOP_RIGHT);
lv_obj_set_width( ui_FOVCUSTOM_TOP_RIGHT, lv_pct(25));
lv_obj_set_height( ui_FOVCUSTOM_TOP_RIGHT, lv_pct(25));
lv_obj_set_x( ui_FOVCUSTOM_TOP_RIGHT, lv_pct(30) );
lv_obj_set_y( ui_FOVCUSTOM_TOP_RIGHT, lv_pct(-35) );
lv_obj_set_align( ui_FOVCUSTOM_TOP_RIGHT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCUSTOM_TOP_RIGHT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCUSTOM_TOP_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCUSTOM_TOP_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCUSTOM_TOP_RIGHT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCUSTOM_CENTER = lv_obj_create(ui_FOVCUSTOM_Space);
lv_obj_remove_style_all(ui_FOVCUSTOM_CENTER);
lv_obj_set_width( ui_FOVCUSTOM_CENTER, lv_pct(80));
lv_obj_set_height( ui_FOVCUSTOM_CENTER, lv_pct(30));
lv_obj_set_align( ui_FOVCUSTOM_CENTER, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCUSTOM_CENTER, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCUSTOM_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCUSTOM_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCUSTOM_CENTER, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCUSTOM_BOTTOM_LEFT = lv_obj_create(ui_FOVCUSTOM_Space);
lv_obj_remove_style_all(ui_FOVCUSTOM_BOTTOM_LEFT);
lv_obj_set_width( ui_FOVCUSTOM_BOTTOM_LEFT, lv_pct(25));
lv_obj_set_height( ui_FOVCUSTOM_BOTTOM_LEFT, lv_pct(25));
lv_obj_set_x( ui_FOVCUSTOM_BOTTOM_LEFT, lv_pct(-30) );
lv_obj_set_y( ui_FOVCUSTOM_BOTTOM_LEFT, lv_pct(35) );
lv_obj_set_align( ui_FOVCUSTOM_BOTTOM_LEFT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCUSTOM_BOTTOM_LEFT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCUSTOM_BOTTOM_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCUSTOM_BOTTOM_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCUSTOM_BOTTOM_LEFT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCUSTOM_BOTTOM_MIDDLE = lv_obj_create(ui_FOVCUSTOM_Space);
lv_obj_remove_style_all(ui_FOVCUSTOM_BOTTOM_MIDDLE);
lv_obj_set_width( ui_FOVCUSTOM_BOTTOM_MIDDLE, lv_pct(25));
lv_obj_set_height( ui_FOVCUSTOM_BOTTOM_MIDDLE, lv_pct(25));
lv_obj_set_x( ui_FOVCUSTOM_BOTTOM_MIDDLE, lv_pct(0) );
lv_obj_set_y( ui_FOVCUSTOM_BOTTOM_MIDDLE, lv_pct(35) );
lv_obj_set_align( ui_FOVCUSTOM_BOTTOM_MIDDLE, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCUSTOM_BOTTOM_MIDDLE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCUSTOM_BOTTOM_MIDDLE, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCUSTOM_BOTTOM_MIDDLE, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCUSTOM_BOTTOM_MIDDLE, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVCUSTOM_BOTTOM_RIGHT = lv_obj_create(ui_FOVCUSTOM_Space);
lv_obj_remove_style_all(ui_FOVCUSTOM_BOTTOM_RIGHT);
lv_obj_set_width( ui_FOVCUSTOM_BOTTOM_RIGHT, lv_pct(25));
lv_obj_set_height( ui_FOVCUSTOM_BOTTOM_RIGHT, lv_pct(25));
lv_obj_set_x( ui_FOVCUSTOM_BOTTOM_RIGHT, lv_pct(30) );
lv_obj_set_y( ui_FOVCUSTOM_BOTTOM_RIGHT, lv_pct(35) );
lv_obj_set_align( ui_FOVCUSTOM_BOTTOM_RIGHT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVCUSTOM_BOTTOM_RIGHT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVCUSTOM_BOTTOM_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVCUSTOM_BOTTOM_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVCUSTOM_BOTTOM_RIGHT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVRACE_Space = lv_obj_create(ui_MainScreen1);
lv_obj_remove_style_all(ui_FOVRACE_Space);
lv_obj_set_height( ui_FOVRACE_Space, 968);
lv_obj_set_width( ui_FOVRACE_Space, lv_pct(100));
lv_obj_set_align( ui_FOVRACE_Space, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_FOVRACE_Space, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_FOVRACE_Space, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVRACE_Space, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVRACE_Space, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVRACE_Space, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVRACE_BOTTOM_LEFT = lv_obj_create(ui_FOVRACE_Space);
lv_obj_remove_style_all(ui_FOVRACE_BOTTOM_LEFT);
lv_obj_set_width( ui_FOVRACE_BOTTOM_LEFT, lv_pct(35));
lv_obj_set_height( ui_FOVRACE_BOTTOM_LEFT, lv_pct(20));
lv_obj_set_x( ui_FOVRACE_BOTTOM_LEFT, lv_pct(-25) );
lv_obj_set_y( ui_FOVRACE_BOTTOM_LEFT, lv_pct(35) );
lv_obj_set_align( ui_FOVRACE_BOTTOM_LEFT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVRACE_BOTTOM_LEFT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVRACE_BOTTOM_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVRACE_BOTTOM_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVRACE_BOTTOM_LEFT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVRACE_MIDDLE_RIGHT = lv_obj_create(ui_FOVRACE_Space);
lv_obj_remove_style_all(ui_FOVRACE_MIDDLE_RIGHT);
lv_obj_set_width( ui_FOVRACE_MIDDLE_RIGHT, lv_pct(35));
lv_obj_set_height( ui_FOVRACE_MIDDLE_RIGHT, lv_pct(20));
lv_obj_set_x( ui_FOVRACE_MIDDLE_RIGHT, lv_pct(25) );
lv_obj_set_y( ui_FOVRACE_MIDDLE_RIGHT, lv_pct(12) );
lv_obj_set_align( ui_FOVRACE_MIDDLE_RIGHT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVRACE_MIDDLE_RIGHT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVRACE_MIDDLE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVRACE_MIDDLE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVRACE_MIDDLE_RIGHT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVRACE_CENTER = lv_obj_create(ui_FOVRACE_Space);
lv_obj_remove_style_all(ui_FOVRACE_CENTER);
lv_obj_set_width( ui_FOVRACE_CENTER, lv_pct(80));
lv_obj_set_height( ui_FOVRACE_CENTER, lv_pct(25));
lv_obj_set_x( ui_FOVRACE_CENTER, lv_pct(0) );
lv_obj_set_y( ui_FOVRACE_CENTER, lv_pct(-13) );
lv_obj_set_align( ui_FOVRACE_CENTER, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVRACE_CENTER, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVRACE_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVRACE_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVRACE_CENTER, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVRACE_BOTTOM_RIGHT = lv_obj_create(ui_FOVRACE_Space);
lv_obj_remove_style_all(ui_FOVRACE_BOTTOM_RIGHT);
lv_obj_set_width( ui_FOVRACE_BOTTOM_RIGHT, lv_pct(35));
lv_obj_set_height( ui_FOVRACE_BOTTOM_RIGHT, lv_pct(20));
lv_obj_set_x( ui_FOVRACE_BOTTOM_RIGHT, lv_pct(25) );
lv_obj_set_y( ui_FOVRACE_BOTTOM_RIGHT, lv_pct(35) );
lv_obj_set_align( ui_FOVRACE_BOTTOM_RIGHT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVRACE_BOTTOM_RIGHT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVRACE_BOTTOM_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVRACE_BOTTOM_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVRACE_BOTTOM_RIGHT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVRACE_MIDDLE_LEFT = lv_obj_create(ui_FOVRACE_Space);
lv_obj_remove_style_all(ui_FOVRACE_MIDDLE_LEFT);
lv_obj_set_width( ui_FOVRACE_MIDDLE_LEFT, lv_pct(35));
lv_obj_set_height( ui_FOVRACE_MIDDLE_LEFT, lv_pct(20));
lv_obj_set_x( ui_FOVRACE_MIDDLE_LEFT, lv_pct(-25) );
lv_obj_set_y( ui_FOVRACE_MIDDLE_LEFT, lv_pct(12) );
lv_obj_set_align( ui_FOVRACE_MIDDLE_LEFT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVRACE_MIDDLE_LEFT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVRACE_MIDDLE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVRACE_MIDDLE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVRACE_MIDDLE_LEFT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FOVRACE_TOP_RIGHT = lv_obj_create(ui_FOVRACE_Space);
lv_obj_remove_style_all(ui_FOVRACE_TOP_RIGHT);
lv_obj_set_width( ui_FOVRACE_TOP_RIGHT, lv_pct(35));
lv_obj_set_height( ui_FOVRACE_TOP_RIGHT, lv_pct(20));
lv_obj_set_x( ui_FOVRACE_TOP_RIGHT, lv_pct(25) );
lv_obj_set_y( ui_FOVRACE_TOP_RIGHT, lv_pct(-38) );
lv_obj_set_align( ui_FOVRACE_TOP_RIGHT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_FOVRACE_TOP_RIGHT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_FOVRACE_TOP_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_DEVHIGHLIGHT);
ui_object_set_themeable_style_property(ui_FOVRACE_TOP_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_DEVHIGHLIGHT);
lv_obj_set_style_border_width(ui_FOVRACE_TOP_RIGHT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);


}
