// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Zoka_GUI

#include "../ui.h"

void ui_SelectionMenu_screen_init(void)
{
ui_SelectionMenu = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SelectionMenu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SelectionMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SelectionMenu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ModeSelectionPanel = lv_obj_create(ui_SelectionMenu);
lv_obj_set_width( ui_ModeSelectionPanel, 150);
lv_obj_set_height( ui_ModeSelectionPanel, lv_pct(59));
lv_obj_set_align( ui_ModeSelectionPanel, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_ModeSelectionPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ModeSelectionPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_STATUSBARBG);
ui_object_set_themeable_style_property(ui_ModeSelectionPanel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_STATUSBARBG);
lv_obj_set_style_border_width(ui_ModeSelectionPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Selection = lv_obj_create(ui_ModeSelectionPanel);
lv_obj_set_width( ui_Selection, 156);
lv_obj_set_height( ui_Selection, 110);
lv_obj_set_x( ui_Selection, 4 );
lv_obj_set_y( ui_Selection, -249 );
lv_obj_set_align( ui_Selection, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Selection, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Selection, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Selection, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Selection, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ModeContainer = lv_obj_create(ui_ModeSelectionPanel);
lv_obj_remove_style_all(ui_ModeContainer);
lv_obj_set_width( ui_ModeContainer, lv_pct(120));
lv_obj_set_height( ui_ModeContainer, lv_pct(105));
lv_obj_set_align( ui_ModeContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_ModeContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ModeContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ModeContainer, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_Navigation = lv_img_create(ui_ModeContainer);
lv_img_set_src(ui_Navigation, &ui_img_navigation_png);
lv_obj_set_width( ui_Navigation, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Navigation, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Navigation, 0 );
lv_obj_set_y( ui_Navigation, -240 );
lv_obj_set_align( ui_Navigation, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Navigation, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Navigation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Navigation,-200);
lv_img_set_zoom(ui_Navigation,80);
ui_object_set_themeable_style_property(ui_Navigation, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_Navigation, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_PRIMARY);

ui_Racetrack = lv_img_create(ui_ModeContainer);
lv_img_set_src(ui_Racetrack, &ui_img_865313178);
lv_obj_set_width( ui_Racetrack, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Racetrack, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Racetrack, 1 );
lv_obj_set_y( ui_Racetrack, -95 );
lv_obj_set_align( ui_Racetrack, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Racetrack, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Racetrack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Racetrack,80);
lv_obj_set_style_img_recolor(ui_Racetrack, lv_color_hex(0xFF6900), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Racetrack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Flag = lv_img_create(ui_Racetrack);
lv_img_set_src(ui_Flag, &ui_img_course_png);
lv_obj_set_width( ui_Flag, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Flag, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Flag, -38 );
lv_obj_set_y( ui_Flag, -24 );
lv_obj_set_align( ui_Flag, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Flag, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Flag, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Flag,50);
ui_object_set_themeable_style_property(ui_Flag, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_Flag, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_PRIMARY);

ui_Cycling = lv_img_create(ui_ModeContainer);
lv_img_set_src(ui_Cycling, &ui_img_cycle_png);
lv_obj_set_width( ui_Cycling, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Cycling, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Cycling, 0 );
lv_obj_set_y( ui_Cycling, -240 );
lv_obj_set_align( ui_Cycling, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Cycling, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Cycling, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Cycling,80);
ui_object_set_themeable_style_property(ui_Cycling, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_Cycling, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_PRIMARY);

ui_Custom = lv_img_create(ui_ModeContainer);
lv_img_set_src(ui_Custom, &ui_img_user_png);
lv_obj_set_width( ui_Custom, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Custom, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Custom, 0 );
lv_obj_set_y( ui_Custom, -240 );
lv_obj_set_align( ui_Custom, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Custom, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Custom, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Custom,80);
ui_object_set_themeable_style_property(ui_Custom, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_Custom, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_PRIMARY);

ui_ActivateMenu = lv_btn_create(ui_SelectionMenu);
lv_obj_set_width( ui_ActivateMenu, 100);
lv_obj_set_height( ui_ActivateMenu, 50);
lv_obj_set_x( ui_ActivateMenu, -239 );
lv_obj_set_y( ui_ActivateMenu, -345 );
lv_obj_set_align( ui_ActivateMenu, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ActivateMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ActivateMenu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ActivateMenu, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_ActivateMenu, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_PRIMARY);

ui_DeactivateMenu = lv_btn_create(ui_SelectionMenu);
lv_obj_set_width( ui_DeactivateMenu, 100);
lv_obj_set_height( ui_DeactivateMenu, 50);
lv_obj_set_x( ui_DeactivateMenu, -43 );
lv_obj_set_y( ui_DeactivateMenu, -345 );
lv_obj_set_align( ui_DeactivateMenu, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DeactivateMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_DeactivateMenu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonMoveModeMenuSelectionUp = lv_btn_create(ui_SelectionMenu);
lv_obj_set_width( ui_ButtonMoveModeMenuSelectionUp, 100);
lv_obj_set_height( ui_ButtonMoveModeMenuSelectionUp, 50);
lv_obj_set_x( ui_ButtonMoveModeMenuSelectionUp, -130 );
lv_obj_set_y( ui_ButtonMoveModeMenuSelectionUp, -410 );
lv_obj_set_align( ui_ButtonMoveModeMenuSelectionUp, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonMoveModeMenuSelectionUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonMoveModeMenuSelectionUp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ButtonMoveModeMenuSelectionUp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_ButtonMoveModeMenuSelectionUp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_PRIMARY);

ui_ButtonMoveModeMenuSelectionDown = lv_btn_create(ui_SelectionMenu);
lv_obj_set_width( ui_ButtonMoveModeMenuSelectionDown, 100);
lv_obj_set_height( ui_ButtonMoveModeMenuSelectionDown, 50);
lv_obj_set_x( ui_ButtonMoveModeMenuSelectionDown, -139 );
lv_obj_set_y( ui_ButtonMoveModeMenuSelectionDown, -286 );
lv_obj_set_align( ui_ButtonMoveModeMenuSelectionDown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonMoveModeMenuSelectionDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonMoveModeMenuSelectionDown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ButtonMoveModeMenuSelectionDown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_ButtonMoveModeMenuSelectionDown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_PRIMARY);

ui_ButtonSelectModeMenuSelection = lv_btn_create(ui_SelectionMenu);
lv_obj_set_width( ui_ButtonSelectModeMenuSelection, 100);
lv_obj_set_height( ui_ButtonSelectModeMenuSelection, 50);
lv_obj_set_x( ui_ButtonSelectModeMenuSelection, -132 );
lv_obj_set_y( ui_ButtonSelectModeMenuSelection, -139 );
lv_obj_set_align( ui_ButtonSelectModeMenuSelection, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonSelectModeMenuSelection, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonSelectModeMenuSelection, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ButtonSelectModeMenuSelection, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_PRIMARY);
ui_object_set_themeable_style_property(ui_ButtonSelectModeMenuSelection, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_PRIMARY);

lv_obj_add_event_cb(ui_ActivateMenu, ui_event_ActivateMenu, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DeactivateMenu, ui_event_DeactivateMenu, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonMoveModeMenuSelectionUp, ui_event_ButtonMoveModeMenuSelectionUp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonMoveModeMenuSelectionDown, ui_event_ButtonMoveModeMenuSelectionDown, LV_EVENT_ALL, NULL);

}
