// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Zoka_GUI

#ifndef _UI_COMP_STATUSBAR_H
#define _UI_COMP_STATUSBAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT StatusBar
#define UI_COMP_STATUSBAR_STATUSBAR 0
#define UI_COMP_STATUSBAR_ZOKABATTERYIMAGE 1
#define UI_COMP_STATUSBAR_ZOKABATTERYIMAGE_ZOKABATTERYBAR 2
#define UI_COMP_STATUSBAR_TIME 3
#define UI_COMP_STATUSBAR_PHONEBATTERYIMAGE 4
#define UI_COMP_STATUSBAR_PHONEBATTERYIMAGE_PHONEBATTERYBAR 5
#define _UI_COMP_STATUSBAR_NUM 6
lv_obj_t *ui_StatusBar_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
