// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Zoka_GUI

#ifndef _ZOKA_GUI_UI_H
#define _ZOKA_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void ActivateModeMenu_Animation( lv_obj_t *TargetObject, int delay);
void DeactivateModeMenu_Animation( lv_obj_t *TargetObject, int delay);
void ModeMenuMoveSelectionDown_Animation( lv_obj_t *TargetObject, int delay);
void ModeMenuMoveSelectionUp_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_BootScreen
void ui_BootScreen_screen_init(void);
extern lv_obj_t *ui_BootScreen;
extern lv_obj_t *ui_BootImage;
extern lv_obj_t *ui_BootBar;
// SCREEN: ui_SelectionMenu
void ui_SelectionMenu_screen_init(void);
extern lv_obj_t *ui_SelectionMenu;
extern lv_obj_t *ui_ModeSelectionPanel;
extern lv_obj_t *ui_Selection;
extern lv_obj_t *ui_ModeContainer;
extern lv_obj_t *ui_Navigation;
extern lv_obj_t *ui_Racetrack;
extern lv_obj_t *ui_Flag;
extern lv_obj_t *ui_Cycling;
extern lv_obj_t *ui_Custom;
void ui_event_ActivateMenu( lv_event_t * e);
extern lv_obj_t *ui_ActivateMenu;
void ui_event_DeactivateMenu( lv_event_t * e);
extern lv_obj_t *ui_DeactivateMenu;
void ui_event_ButtonMoveModeMenuSelectionUp( lv_event_t * e);
extern lv_obj_t *ui_ButtonMoveModeMenuSelectionUp;
void ui_event_ButtonMoveModeMenuSelectionDown( lv_event_t * e);
extern lv_obj_t *ui_ButtonMoveModeMenuSelectionDown;
extern lv_obj_t *ui_ButtonSelectModeMenuSelection;
// SCREEN: ui_ConnectScreen
void ui_ConnectScreen_screen_init(void);
extern lv_obj_t *ui_ConnectScreen;
extern lv_obj_t *ui_VisibleArea;
extern lv_obj_t *ui_iPhone1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_MountedIcon1;
extern lv_obj_t *ui_Zoka;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Spinner2;
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_VisibleArea1;
extern lv_obj_t *ui_StatusBar1;
extern lv_obj_t *ui_ZokaBattContainer1;
extern lv_obj_t *ui_ZokaBatteryImage1;
extern lv_obj_t *ui_ZokaBatteryBar1;
extern lv_obj_t *ui_ZokaBatteryPercent1;
extern lv_obj_t *ui_Time1;
extern lv_obj_t *ui_PhoneBattContainer1;
extern lv_obj_t *ui_PhoneBatteryImage1;
extern lv_obj_t *ui_PhoneBatteryBar1;
extern lv_obj_t *ui_PhoneBatteryPercent1;
extern lv_obj_t *ui_FOV_Navigation1;
extern lv_obj_t *ui_FOVNAV_TOP_LEFT1;
extern lv_obj_t *ui_TimeOfArival1;
extern lv_obj_t *ui_FOVNAV_TOP_MIDDLE1;
extern lv_obj_t *ui_TimeRemaining1;
extern lv_obj_t *ui_FOVNAV_TOP_RIGHT1;
extern lv_obj_t *ui_RemainingDistance1;
extern lv_obj_t *ui_RemainingDistanceUnit;
extern lv_obj_t *ui_FOVNAV_CENTER1;
extern lv_obj_t *ui_FOVNAV_BOTTOM_LEFT1;
extern lv_obj_t *ui_ArcSpeed1;
extern lv_obj_t *ui_SpeedLabel1;
extern lv_obj_t *ui_UnitLabel1;
extern lv_obj_t *ui_FONAV_BOTTOM_RIGHT1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_SpeedLimitLabel1;
extern lv_obj_t *ui_FOVCYCLING_Space1;
extern lv_obj_t *ui_FOVCYCLING_TOP_LEFT1;
extern lv_obj_t *ui_FOVCYCLING_TOP_RIGHT1;
extern lv_obj_t *ui_FOVCYCLING_CENTER1;
extern lv_obj_t *ui_FOVCYCLING_BOTTOM_LEFT1;
extern lv_obj_t *ui_FOVCYCLING_BOTTOM_MIDDLE1;
extern lv_obj_t *ui_FOVCYCLING_BOTTOM_RIGHT1;
extern lv_obj_t *ui_FOVCUSTOM_Space1;
extern lv_obj_t *ui_FOVCUSTOM_TOP_LEFT1;
extern lv_obj_t *ui_FOVCUSTOM_TOP_MIDDLE1;
extern lv_obj_t *ui_FOVCUSTOM_TOP_RIGHT1;
extern lv_obj_t *ui_FOVCUSTOM_CENTER1;
extern lv_obj_t *ui_FOVCUSTOM_BOTTOM_LEFT1;
extern lv_obj_t *ui_FOVCUSTOM_BOTTOM_MIDDLE1;
extern lv_obj_t *ui_FOVCUSTOM_BOTTOM_RIGHT1;
extern lv_obj_t *ui_FOVRACE_Space1;
extern lv_obj_t *ui_FOVRACE_BOTTOM_LEFT1;
extern lv_obj_t *ui_FOVRACE_MIDDLE_RIGHT1;
extern lv_obj_t *ui_FOVRACE_CENTER1;
extern lv_obj_t *ui_FOVRACE_BOTTOM_RIGHT1;
extern lv_obj_t *ui_FOVRACE_MIDDLE_LEFT1;
extern lv_obj_t *ui_FOVRACE_TOP_RIGHT1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_m_png);   // assets/M.png
LV_IMG_DECLARE( ui_img_1513849953);   // assets/battery-full-outline.png
LV_IMG_DECLARE( ui_img_speed_limit_png);   // assets/speed_limit.png
LV_IMG_DECLARE( ui_img_navigation_png);   // assets/navigation.png
LV_IMG_DECLARE( ui_img_865313178);   // assets/voiture-de-sport.png
LV_IMG_DECLARE( ui_img_course_png);   // assets/course.png
LV_IMG_DECLARE( ui_img_cycle_png);   // assets/cycle.png
LV_IMG_DECLARE( ui_img_user_png);   // assets/user.png
LV_IMG_DECLARE( ui_img_iphonex_png);   // assets/iPhoneX.png
LV_IMG_DECLARE( ui_img_zoka_front_small_png);   // assets/Zoka_front_small.png
LV_IMG_DECLARE( ui_img_285769805);   // assets/indicateur-de-signal-bluetooth.png


LV_FONT_DECLARE( ui_font_Lexend32);
LV_FONT_DECLARE( ui_font_Lexend50);
LV_FONT_DECLARE( ui_font_Lexend24);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
