// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Zoka_GUI

#ifndef _ZOKA_GUI_UI_H
#define _ZOKA_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void ActivateModeMenu_Animation( lv_obj_t *TargetObject, int delay);
void DeactivateModeMenu_Animation( lv_obj_t *TargetObject, int delay);
void ModeMenuMoveSelectionDown_Animation( lv_obj_t *TargetObject, int delay);
void ModeMenuMoveSelectionUp_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_BootScreen
void ui_BootScreen_screen_init(void);
extern lv_obj_t *ui_BootScreen;
extern lv_obj_t *ui_BootImage;
extern lv_obj_t *ui_BootBar;
// SCREEN: ui_MainScreen1
void ui_MainScreen1_screen_init(void);
extern lv_obj_t *ui_MainScreen1;
extern lv_obj_t *ui_StatusBar;
extern lv_obj_t *ui_AltitudeRoller1;
extern lv_obj_t *ui_FOV_Navigation;
extern lv_obj_t *ui_FOVNAV_TOP_LEFT;
extern lv_obj_t *ui_TimeOfArival;
extern lv_obj_t *ui_FOVNAV_TOP_MIDDLE;
extern lv_obj_t *ui_TImeRemaining;
extern lv_obj_t *ui_FOVNAV_TOP_RIGHT;
extern lv_obj_t *ui_RemainingDistance;
extern lv_obj_t *ui_FOVNAV_CENTER;
extern lv_obj_t *ui_FOVNAV_BOTTOM_LEFT;
extern lv_obj_t *ui_ArcSpeed;
extern lv_obj_t *ui_SpeedLabel;
extern lv_obj_t *ui_UnitLabel;
extern lv_obj_t *ui_FONAV_BOTTOM_RIGHT;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_SpeedLimitLabel;
extern lv_obj_t *ui_FOVCYCLING_Space;
extern lv_obj_t *ui_FOVCYCLING_TOP_LEFT;
extern lv_obj_t *ui_FOVCYCLING_TOP_RIGHT;
extern lv_obj_t *ui_FOVCYCLING_CENTER;
extern lv_obj_t *ui_FOVCYCLING_BOTTOM_LEFT;
extern lv_obj_t *ui_FOVCYCLING_BOTTOM_MIDDLE;
extern lv_obj_t *ui_FOVCYCLING_BOTTOM_RIGHT;
extern lv_obj_t *ui_FOVCUSTOM_Space;
extern lv_obj_t *ui_FOVCUSTOM_TOP_LEFT;
extern lv_obj_t *ui_FOVCUSTOM_TOP_MIDDLE;
extern lv_obj_t *ui_FOVCUSTOM_TOP_RIGHT;
extern lv_obj_t *ui_FOVCUSTOM_CENTER;
extern lv_obj_t *ui_FOVCUSTOM_BOTTOM_LEFT;
extern lv_obj_t *ui_FOVCUSTOM_BOTTOM_MIDDLE;
extern lv_obj_t *ui_FOVCUSTOM_BOTTOM_RIGHT;
extern lv_obj_t *ui_FOVRACE_Space;
extern lv_obj_t *ui_FOVRACE_BOTTOM_LEFT;
extern lv_obj_t *ui_FOVRACE_MIDDLE_RIGHT;
extern lv_obj_t *ui_FOVRACE_CENTER;
extern lv_obj_t *ui_FOVRACE_BOTTOM_RIGHT;
extern lv_obj_t *ui_FOVRACE_MIDDLE_LEFT;
extern lv_obj_t *ui_FOVRACE_TOP_RIGHT;
// SCREEN: ui_SelectionMenu
void ui_SelectionMenu_screen_init(void);
extern lv_obj_t *ui_SelectionMenu;
extern lv_obj_t *ui_ModeSelectionPanel;
extern lv_obj_t *ui_Selection;
extern lv_obj_t *ui_ModeContainer;
extern lv_obj_t *ui_Navigation;
extern lv_obj_t *ui_Racetrack;
extern lv_obj_t *ui_Flag;
extern lv_obj_t *ui_Cycling;
extern lv_obj_t *ui_Custom;
void ui_event_ActivateMenu( lv_event_t * e);
extern lv_obj_t *ui_ActivateMenu;
void ui_event_DeactivateMenu( lv_event_t * e);
extern lv_obj_t *ui_DeactivateMenu;
void ui_event_ButtonMoveModeMenuSelectionUp( lv_event_t * e);
extern lv_obj_t *ui_ButtonMoveModeMenuSelectionUp;
void ui_event_ButtonMoveModeMenuSelectionDown( lv_event_t * e);
extern lv_obj_t *ui_ButtonMoveModeMenuSelectionDown;
extern lv_obj_t *ui_ButtonSelectModeMenuSelection;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_m_png);   // assets/M.png
LV_IMG_DECLARE( ui_img_1513849953);   // assets/battery-full-outline.png
LV_IMG_DECLARE( ui_img_speed_limit_png);   // assets/speed_limit.png
LV_IMG_DECLARE( ui_img_navigation_png);   // assets/navigation.png
LV_IMG_DECLARE( ui_img_865313178);   // assets/voiture-de-sport.png
LV_IMG_DECLARE( ui_img_course_png);   // assets/course.png
LV_IMG_DECLARE( ui_img_cycle_png);   // assets/cycle.png
LV_IMG_DECLARE( ui_img_user_png);   // assets/user.png


LV_FONT_DECLARE( ui_font_Lexend50);
LV_FONT_DECLARE( ui_font_Lexend32);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
