// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Zoka_GUI

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_PRIMARY[1] = {0xFF6900};
const ui_theme_variable_t _ui_theme_alpha_PRIMARY[1] = {255};

const ui_theme_variable_t _ui_theme_color_STATUSBARBG[1] = {0x666666};
const ui_theme_variable_t _ui_theme_alpha_STATUSBARBG[1] = {255};

const ui_theme_variable_t _ui_theme_color_SECONDARY[1] = {0x888888};
const ui_theme_variable_t _ui_theme_alpha_SECONDARY[1] = {255};

const ui_theme_variable_t _ui_theme_color_STATUSBARPRIMARY[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_STATUSBARPRIMARY[1] = {255};

const ui_theme_variable_t _ui_theme_color_DEVHIGHLIGHT[1] = {0xFF0000};
const ui_theme_variable_t _ui_theme_alpha_DEVHIGHLIGHT[1] = {0};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

